export const ROUTES = {
  home: "/",
  catalogue: "/catalogue",
  productDetail: (slug = ":slug") => `/produits/${slug}`,
  cart: "/panier",
  checkout: "/commande",
  orderConfirmation: (orderNumber = ":orderNumber") => `/confirmation/${orderNumber}`,
  about: "/a-propos",
  contact: "/contact",
  termsOfSale: "/cgv",
  privacyPolicy: "/confidentialite",
  legalNotice: "/mentions-legales",

  ownerLogin: "/proprietaire/connexion",
  ownerDashboard: "/proprietaire/tableau-de-bord",
  ownerProducts: "/proprietaire/produits",
  ownerProductNew: "/proprietaire/produits/nouveau",
  ownerProductEdit: (id = ":id") => `/proprietaire/produits/${id}`,
  ownerCategories: "/proprietaire/categories",
  ownerStock: "/proprietaire/stock",
  ownerOrders: "/proprietaire/commandes",
  ownerOrderDetail: (id = ":id") => `/proprietaire/commandes/${id}`,
  ownerMessages: "/proprietaire/messages",
  ownerMessageDetail: (id = ":id") => `/proprietaire/messages/${id}`,
  ownerStatistics: "/proprietaire/statistiques",
  ownerProfile: "/proprietaire/profil",

  adminLogin: "/admin/connexion",
  adminDashboard: "/admin/tableau-de-bord",
  adminOwnerAccounts: "/admin/comptes-proprietaires",
  adminOwnerAccountNew: "/admin/comptes-proprietaires/nouveau",
  adminOwnerAccountEdit: (id = ":id") => `/admin/comptes-proprietaires/${id}`,
  adminActivityLog: "/admin/journal-activite",
  adminStatistics: "/admin/statistiques",
  adminSettings: "/admin/parametres",
  adminProfile: "/admin/profil",
};
